
-- Create crm_activities table
CREATE TABLE IF NOT EXISTS crm_activities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lead_id BIGINT NOT NULL REFERENCES leads(id) ON DELETE CASCADE,
    type TEXT NOT NULL CHECK (type IN ('note', 'call', 'email', 'meeting', 'status_change', 'whatsapp')),
    title TEXT NOT NULL,
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    created_by UUID REFERENCES auth.users(id)
);

-- Index for faster lookups
CREATE INDEX IF NOT EXISTS idx_crm_activities_lead_id ON crm_activities(lead_id);

-- RLS Policies
ALTER TABLE crm_activities ENABLE ROW LEVEL SECURITY;

-- Allow read access to authenticated users (could be stricter based on role)
CREATE POLICY "Enable read access for authenticated users" ON crm_activities
    FOR SELECT
    TO authenticated
    USING (true);

-- Allow insert access to authenticated users
CREATE POLICY "Enable insert access for authenticated users" ON crm_activities
    FOR INSERT
    TO authenticated
    WITH CHECK (true);
