-- User-specific checklist layout (per-user move/order)
CREATE TABLE IF NOT EXISTS public.user_checklist_layout (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    checklist_template_id BIGINT NOT NULL REFERENCES public.checklist_templates(id) ON DELETE CASCADE,
    folder_id BIGINT REFERENCES public.checklist_folders(id) ON DELETE SET NULL,
    display_order INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- One layout row per user+template
CREATE UNIQUE INDEX IF NOT EXISTS idx_user_checklist_layout_unique
    ON public.user_checklist_layout(user_id, checklist_template_id);

-- Helpful indexes
CREATE INDEX IF NOT EXISTS idx_user_checklist_layout_user_id
    ON public.user_checklist_layout(user_id);
CREATE INDEX IF NOT EXISTS idx_user_checklist_layout_folder_id
    ON public.user_checklist_layout(folder_id);

-- Enable RLS
ALTER TABLE public.user_checklist_layout ENABLE ROW LEVEL SECURITY;

-- RLS: user can manage own layout only
DROP POLICY IF EXISTS "user_checklist_layout_select" ON public.user_checklist_layout;
DROP POLICY IF EXISTS "user_checklist_layout_insert" ON public.user_checklist_layout;
DROP POLICY IF EXISTS "user_checklist_layout_update" ON public.user_checklist_layout;
DROP POLICY IF EXISTS "user_checklist_layout_delete" ON public.user_checklist_layout;

CREATE POLICY "user_checklist_layout_select" ON public.user_checklist_layout
    FOR SELECT USING (user_id = COALESCE(auth.uid(), current_user_id()));

CREATE POLICY "user_checklist_layout_insert" ON public.user_checklist_layout
    FOR INSERT WITH CHECK (user_id = COALESCE(auth.uid(), current_user_id()));

CREATE POLICY "user_checklist_layout_update" ON public.user_checklist_layout
    FOR UPDATE USING (user_id = COALESCE(auth.uid(), current_user_id()))
    WITH CHECK (user_id = COALESCE(auth.uid(), current_user_id()));

CREATE POLICY "user_checklist_layout_delete" ON public.user_checklist_layout
    FOR DELETE USING (user_id = COALESCE(auth.uid(), current_user_id()));
