-- Migration: Create inspection_atas tables for continuous audio recording (ATA)
-- This allows technicians to record a continuous audio throughout the inspection
-- and generate a formatted transcript document (ATA)

-- ============================================================================
-- Table: inspection_atas
-- Main table to store ATA metadata and generated content
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.inspection_atas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inspection_id BIGINT NOT NULL REFERENCES public.inspections(id) ON DELETE CASCADE,
    organization_id BIGINT REFERENCES public.organizations(id) ON DELETE CASCADE,
    created_by UUID REFERENCES auth.users(id),

    -- Status workflow: recording -> processing -> draft -> validated
    status TEXT DEFAULT 'recording' CHECK (status IN ('recording', 'processing', 'draft', 'validated')),

    -- Audio metadata
    total_duration_seconds INTEGER DEFAULT 0,

    -- AI-generated content
    transcript TEXT,                    -- Full transcription with timestamps
    summary TEXT,                       -- Executive summary
    identified_items JSONB DEFAULT '[]', -- Items identified from audio: [{item_id, status, observation}]

    -- Final document
    doc_url TEXT,                       -- URL to generated .docx file

    -- Timestamps
    created_at TIMESTAMPTZ DEFAULT NOW(),
    validated_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================================
-- Table: inspection_ata_segments
-- Stores individual audio segments (for pause/resume functionality)
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.inspection_ata_segments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ata_id BIGINT NOT NULL REFERENCES public.inspection_atas(id) ON DELETE CASCADE,
    segment_number INTEGER NOT NULL,

    -- Audio storage
    audio_url TEXT,                     -- URL in Supabase Storage
    duration_seconds INTEGER DEFAULT 0,

    -- Timing information
    started_at TIMESTAMPTZ,
    ended_at TIMESTAMPTZ,

    -- Upload status (for offline sync)
    uploaded BOOLEAN DEFAULT FALSE,

    -- Timestamps
    created_at TIMESTAMPTZ DEFAULT NOW(),

    -- Ensure unique segment numbers per ATA
    UNIQUE(ata_id, segment_number)
);

-- ============================================================================
-- Indexes for performance
-- ============================================================================
CREATE INDEX IF NOT EXISTS idx_inspection_atas_inspection_id
    ON public.inspection_atas(inspection_id);

CREATE INDEX IF NOT EXISTS idx_inspection_atas_organization_id
    ON public.inspection_atas(organization_id);

CREATE INDEX IF NOT EXISTS idx_inspection_atas_status
    ON public.inspection_atas(status);

CREATE INDEX IF NOT EXISTS idx_inspection_ata_segments_ata_id
    ON public.inspection_ata_segments(ata_id);

-- ============================================================================
-- Trigger: Auto-update updated_at
-- ============================================================================
CREATE OR REPLACE FUNCTION update_inspection_atas_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trigger_update_inspection_atas_updated_at ON public.inspection_atas;
CREATE TRIGGER trigger_update_inspection_atas_updated_at
    BEFORE UPDATE ON public.inspection_atas
    FOR EACH ROW
    EXECUTE FUNCTION update_inspection_atas_updated_at();

-- ============================================================================
-- RLS Policies
-- ============================================================================
ALTER TABLE public.inspection_atas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inspection_ata_segments ENABLE ROW LEVEL SECURITY;

-- Policy: Users can view ATAs from their organization
CREATE POLICY "Users can view ATAs from their organization"
    ON public.inspection_atas
    FOR SELECT
    USING (
        organization_id IN (
            SELECT organization_id FROM public.user_organizations
            WHERE user_id = auth.uid()
        )
    );

-- Policy: Users can insert ATAs for their organization
CREATE POLICY "Users can insert ATAs for their organization"
    ON public.inspection_atas
    FOR INSERT
    WITH CHECK (
        organization_id IN (
            SELECT organization_id FROM public.user_organizations
            WHERE user_id = auth.uid()
        )
    );

-- Policy: Users can update ATAs they created or from their organization
CREATE POLICY "Users can update ATAs from their organization"
    ON public.inspection_atas
    FOR UPDATE
    USING (
        organization_id IN (
            SELECT organization_id FROM public.user_organizations
            WHERE user_id = auth.uid()
        )
    );

-- Policy: Users can delete ATAs they created
CREATE POLICY "Users can delete ATAs they created"
    ON public.inspection_atas
    FOR DELETE
    USING (created_by = auth.uid());

-- Segments policies (inherit from parent ATA)
CREATE POLICY "Users can view segments from their ATAs"
    ON public.inspection_ata_segments
    FOR SELECT
    USING (
        ata_id IN (
            SELECT id FROM public.inspection_atas
            WHERE organization_id IN (
                SELECT organization_id FROM public.user_organizations
                WHERE user_id = auth.uid()
            )
        )
    );

CREATE POLICY "Users can insert segments to their ATAs"
    ON public.inspection_ata_segments
    FOR INSERT
    WITH CHECK (
        ata_id IN (
            SELECT id FROM public.inspection_atas
            WHERE organization_id IN (
                SELECT organization_id FROM public.user_organizations
                WHERE user_id = auth.uid()
            )
        )
    );

CREATE POLICY "Users can update segments from their ATAs"
    ON public.inspection_ata_segments
    FOR UPDATE
    USING (
        ata_id IN (
            SELECT id FROM public.inspection_atas
            WHERE organization_id IN (
                SELECT organization_id FROM public.user_organizations
                WHERE user_id = auth.uid()
            )
        )
    );

CREATE POLICY "Users can delete segments from their ATAs"
    ON public.inspection_ata_segments
    FOR DELETE
    USING (
        ata_id IN (
            SELECT id FROM public.inspection_atas
            WHERE created_by = auth.uid()
        )
    );

-- ============================================================================
-- Storage bucket for ATA audio files
-- ============================================================================
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
    'ata-audio',
    'ata-audio',
    false,
    104857600, -- 100MB limit for longer recordings
    ARRAY['audio/webm', 'audio/mp4', 'audio/mpeg', 'audio/wav', 'audio/ogg']
)
ON CONFLICT (id) DO UPDATE SET
    file_size_limit = EXCLUDED.file_size_limit,
    allowed_mime_types = EXCLUDED.allowed_mime_types;

-- Storage policies for ata-audio bucket
CREATE POLICY "Users can upload ATA audio"
    ON storage.objects
    FOR INSERT
    WITH CHECK (
        bucket_id = 'ata-audio'
        AND auth.role() = 'authenticated'
    );

CREATE POLICY "Users can view their ATA audio"
    ON storage.objects
    FOR SELECT
    USING (
        bucket_id = 'ata-audio'
        AND auth.role() = 'authenticated'
    );

CREATE POLICY "Users can delete their ATA audio"
    ON storage.objects
    FOR DELETE
    USING (
        bucket_id = 'ata-audio'
        AND auth.uid()::text = (storage.foldername(name))[1]
    );

-- ============================================================================
-- Storage bucket for ATA documents (.docx)
-- ============================================================================
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
    'ata-documents',
    'ata-documents',
    false,
    10485760, -- 10MB limit for documents
    ARRAY['application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'application/pdf']
)
ON CONFLICT (id) DO UPDATE SET
    file_size_limit = EXCLUDED.file_size_limit,
    allowed_mime_types = EXCLUDED.allowed_mime_types;

-- Storage policies for ata-documents bucket
CREATE POLICY "Users can upload ATA documents"
    ON storage.objects
    FOR INSERT
    WITH CHECK (
        bucket_id = 'ata-documents'
        AND auth.role() = 'authenticated'
    );

CREATE POLICY "Users can view ATA documents"
    ON storage.objects
    FOR SELECT
    USING (
        bucket_id = 'ata-documents'
        AND auth.role() = 'authenticated'
    );
